# Configurações para ambiente local/desenvolvimento
# Gateway RPC deve ser preferido para comunicação com LCU via Electron

# Configurações customizadas do LCU (usando @ConfigurationProperties)
# @spring-boot-ignore-property: app.lcu.*
app:
  lcu:
    prefer-gateway: true # Priorizar gateway RPC sobre HTTP direto
    host: 127.0.0.1 # Para acesso local ao LCU
    protocol: https
    port: 0 # Será descoberto automaticamente via lockfile
    password: "" # Será configurado via lockfile

# Configuração de banco para desenvolvimento local (MySQL online)
spring:
  datasource:
    # Usar MySQL online para desenvolvimento (mesmo que produção)
    url: ${DATABASE_URL:jdbc:mysql://${MYSQL_HOST:${DB_HOST:localhost}}:${MYSQL_PORT:${DB_PORT:3306}}/${MYSQL_DATABASE:${DB_NAME:lolmatchmaking}}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&connectTimeout=30000&socketTimeout=30000&zeroDateTimeBehavior=convertToNull}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:${DB_USER:root}}
    password: ${MYSQL_PASSWORD:${DB_PASSWORD:password}}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # Usar Liquibase para migrações
    show-sql: false
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: false # Desabilitar temporariamente para testar Discord
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    context-path: /
  websocket:
    max-text-message-buffer-size: 4194304
    max-binary-message-buffer-size: 4194304

# Configurações do DevTools para evitar restarts desnecessários
# spring:
#   devtools:
#     restart:
#       enabled: false # Desabilitar restart automático
#     livereload:
#       enabled: true # Manter LiveReload para frontend
#     additional-paths: src/main/java # Monitorar apenas mudanças em Java

# Logs controlados para debugging
logging:
  level:
    root: INFO
    br.com.lolmatchmaking.backend.service.LCUService: INFO
    br.com.lolmatchmaking.backend.websocket.MatchmakingWebSocketService: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
