# Configurações para ambiente Docker/Containerizado
# Gateway RPC deve ser preferido para comunicação com LCU via Electron

# Configurações customizadas do LCU (usando @ConfigurationProperties)
# @spring-boot-ignore-property: app.lcu.*
app:
  lcu:
    prefer-gateway: true # Priorizar gateway RPC sobre HTTP direto
    host: host.docker.internal # Para acesso ao LCU local via Docker
    protocol: https
    port: 0 # Será descoberto automaticamente via lockfile
    password: "" # Será configurado via lockfile

# Logs controlados para debugging
logging:
  level:
    root: INFO
    "[br.com.lolmatchmaking.backend.service.LCUService]": INFO
    "[br.com.lolmatchmaking.backend.websocket.MatchmakingWebSocketService]": INFO
    "[org.hibernate.SQL]": WARN
    "[org.hibernate.type.descriptor.sql.BasicBinder]": WARN
    "[org.springframework.web]": WARN
    "[org.springframework.security]": WARN
