# Configurações para Google Cloud Run
server:
  port: ${PORT:8080}

spring:
  datasource:
    # O Cloud Run vai receber as variáveis de ambiente
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:wmakeouthill}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

# URLs e endpoints para ambiente Google Cloud
app:
  frontend:
    url: "${FRONTEND_URL:https://fazenda-inhouse-368951732227.southamerica-east1.run.app}"
  backend:
    url: "${BACKEND_URL:https://fazenda-inhouse-368951732227.southamerica-east1.run.app}"
    base-url: "${BACKEND_URL:https://fazenda-inhouse-368951732227.southamerica-east1.run.app}"
    sync:
      enabled: false
  websocket:
    endpoint: "${WS_ENDPOINT:wss://fazenda-inhouse-368951732227.southamerica-east1.run.app/ws}"
  cors:
    allowed-origins:
      - "${FRONTEND_URL:https://fazenda-inhouse-368951732227.southamerica-east1.run.app}"
      - "${BACKEND_URL:https://fazenda-inhouse-368951732227.southamerica-east1.run.app}"
      - "https://*.run.app"
      - "https://fazenda-inhouse-368951732227.southamerica-east1.run.app"
      - "file://"
      - "capacitor://localhost"
      - "http://localhost"
      - "http://localhost:*"
  # ✅ CONFIGURAÇÃO LCU PARA CLOUD RUN
  # O Cloud Run atua como GATEWAY CENTRAL para múltiplos Electron clients
  # Cada Electron client (rodando nos PCs dos jogadores) conecta via WebSocket
  # e envia dados do LCU local para o backend na nuvem
  lcu:
    prefer-gateway: true # ✅ OBRIGATÓRIO: Usar gateway RPC via WebSocket
    host: 127.0.0.1 # Não usado no Cloud Run (cada client tem seu próprio LCU)
    protocol: https # Protocolo dos LCU clients
    port: 0 # Não usado no Cloud Run (cada client tem porta diferente)
    password: "" # Não usado no Cloud Run (cada client tem senha diferente)

# Configurações específicas para Cloud Run
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    br.com.lolmatchmaking: INFO
    root: WARN
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
